CocoaPods/CocoaPods-app

.gitignore
Rakefile

Part of https://github.com/CocoaPods/CocoaPods-app/issues/33.

[Rakefile] Automate creating a GH release

---

app/CocoaPods.xcodeproj/project.pbxproj
app/CocoaPods/Supporting Files/Info.plist
app/Pods/Pods.xcodeproj/project.pbxproj

These changes were made during work pursuant to #52.

Resolve Xcode 7 beta 5 update warnings

---

app/CocoaPods/Supporting Files/Localizable.strings

I have adjusted some of the text that is displayed during the CLI tool installation sequence. Note that since these changes are very subjective, you can feel free to ignore any or all of it.

Touch up UI text

---

Rakefile
app/CocoaPods.xcodeproj/project.pbxproj

Samuel or @kylef - can you try run a release archive on this please? Should turn on code signing for that.

@segiddins => Adds codesigning for release builds - fixes #48

---

app/CocoaPods/Supporting Files/Syntax Definitions/Podfile.plist

Add CocoaPods Keywords to the Podfile Syntax Highlighter

---

app/CocoaPods/CPPodfileConsoleViewController.swift
app/CocoaPods/Podfile.storyboard

This binds the editable property of the textview to a variable in the Podfile Console View Controller

Makes the console view not editable

---

.gitignore
app/CocoaPods/CPAppDelegate.m
app/CocoaPods/CPUserProject.m
app/CocoaPods/Podfile.storyboard

- Add the ruby integration xcode section to gitignore
- Remove storyboard warnings
- Ensure that we dont try open untitled documents

Minor fixes

---

Rakefile
bundle-env
cocoapods-plugins-install/lib/pod/command/plugins/install.rb

Needed for #126 
The bump to RubyGems means a better & faster resolver.

Allow installing multiple plugins at once

---

Rakefile

Ensures up-to-date and setup submodules before running the prerequisites,

Ensures updated submodules when building tooling - fixes #109

---

app/CPReflectionService/CPReflectionService.m
app/CPReflectionService/CPRubyErrors.h
app/CPReflectionService/CPRubyErrors.m
app/CPReflectionService/RBObject+CocoaPods.h
app/CPReflectionService/RBObject+CocoaPods.m
app/CocoaPods/CPPodfileReflection.m

[App/Ruby] Fix reporting in case of a SyntaxError.

---

app/CPReflectionService/CPReflectionService.m
app/CPReflectionService/CPReflectionServiceProtocol.h
app/CPReflectionService/RBObject+CocoaPods.h
app/CPReflectionService/RBObject+CocoaPods.m
app/CPReflectionService/RBObject+CocoaPods.rb
app/CocoaPods/CPPodfileReflection.m

Get a list of installed plugins.

---

Rakefile

I'm leaving it at d for the moment, want to make sure that anyone on a fresh clone can :+1:

Fixes to the rakefile

---

README.markdown

Re comments in https://github.com/CocoaPods/CocoaPods-app/pull/138
Plus the README didn't show `app:prerequisites` but recommended the usage of it.

Updates rake -T and notes for system ruby for the installation

---

app/CocoaPods.xcodeproj/project.pbxproj
app/CocoaPods/Base.lproj/MainMenu.xib
app/CocoaPods/CPMenuVisiblityDirector.swift
app/CocoaPods/CPPodfileViewController.swift
app/CocoaPods/Podfile.storyboard

fixes #144 
Will inline comment.

Consolidates the Menu items

---

.travis.yml
README.markdown
Rakefile
app/CPReflectionService/RBObject+CocoaPods.m
app/CocoaPods.xcodeproj/project.pbxproj
test/Podfile

Refactored bundle build system + Travis support

---

app/CocoaPods/Supporting Files/Syntax Definitions/Podfile.plist

We added some new keywords and options, getting them highlighted :+1:

Update the keywords for 1.0

---

app/CocoaPods/Base.lproj/MainMenu.xib
app/CocoaPods/CPFontAndColourGateKeeper.swift
app/CocoaPods/CPPodfileEditorViewController.swift

Keys: ⌘+ and ⌘-
As discussed in issue #170

Added font increase and decrease options into Editor menu

---

app/CocoaPods/CPPodfileEditorViewController.swift

Changed TAB key ⇥ to indent 2 spaces

---

app/CocoaPods.xcodeproj/project.pbxproj

Allows devs not in the release team to work on the app

Remove code signing for Debug builds

---

app/CocoaPods/CPAppDelegate.m

Close button in Home Window closes the window

---

README.markdown

The title and link were backwards.

Fix markdown link

---

app/CocoaPods/CPXcodeInformationGenerator.m

Updated pretty bundle type for UI Testing Bundle

---

app/CocoaPods.xcodeproj/project.pbxproj
app/CocoaPodsTests/CPMiniSnaphots.swift

Right now this type conversion errors out. I don't think this file is used yet, @orta mentioned it was WIP.

Get the test target building again

---

app/CocoaPods/Base.lproj/MainMenu.xib

Fixes #172 by changing the menu items to specifically mention Podfiles in their titles.

Change open menu items to explicitly mention Podfiles

---

README.markdown
Rakefile

[Rakefile] Automate the PR to Homebrew Cask

---

.gitignore
README.markdown
Rakefile

Handles adding an item to the appcast, and generating the `[release].html`.

Automate creating the sparkle XML

---

Rakefile

Use release date for the app's build version

---

app/CocoaPods/Base.lproj/CPHomeWindowController.xib
app/CocoaPods/Supporting Files/Localizable.strings

As mentioned in #233. 
Now looks like this:
Thoughts?

[Copy] changed wording of home screen buttons 

---

index.html

From http://stackoverflow.com/a/9276879.

Redirect gh-pages index to cocoapods.org/app

---

app/CocoaPods.xcodeproj/project.pbxproj
app/CocoaPods/Supporting Files/main.m
app/CocoaPodsTests/CPStringArrayToSentenceValueTransformerSpec.swift
app/CocoaPodsTests/CPTestHelper.swift
app/CocoaPodsTests/CocoaPodsTests-Bridging-Header.h

Fixes #100.
~~- [ ] Get Travis running tests on the builders~~

More test infrastructure and start writing tests

---

app/CocoaPods/CLI Integrations/CPCLITask.m

Fixes https://github.com/CocoaPods/CocoaPods-app/issues/251

Use 10.10 compatible API for NSProgress

---

Rakefile

[Rakefile] Update cask sparkle checkpoint on release

---

Rakefile
app/CPReflectionService/Info.plist
app/CocoaPods/Supporting Files/Info.plist

Update both Info.plist files with latest version info #trivial

---

app/CocoaPods/CPPodfileViewController.swift

Save the document on any install/update action - fixes #276

---

Rakefile
app/CPReflectionService/Info.plist
app/CocoaPods/CPFontAndColourGateKeeper.swift
app/CocoaPods/CPPodfileEditorViewController.swift
app/CocoaPods/Podfile.storyboard
app/CocoaPods/Supporting Files/Info.plist
app/CocoaPods/Supporting Files/Syntax Definitions/Podfile.plist

Lots of improvements to the auto-complete. 
There's still some weird behaviour where you magically lose a few characters that I've not figured out yet though.

1.0.0.beta.8 + minor misc fixes

---

.gitignore
Rakefile

Pairs with https://github.com/CocoaPods/sparkler/pull/3

[Sparkle] Update feed cache on deploys

---

CHANGELOG.md
Dangerfile
Rakefile
app/CPReflectionService/Info.plist
app/CocoaPods/Supporting Files/Info.plist

OK, deploying was more or less seamless 👍 
Will comment inline.

Updates for deployment

---

README.markdown

[README] Release notes

---

Rakefile
app/CPReflectionService/Info.plist
app/CocoaPods/Supporting Files/Info.plist

Updates the Copyright note that shows up in About CocoaPods.

[Info.plist] Automated Copyright notes #trivial

---

Dangerfile

Adds the magic EOL invisible characters
Uses Danger's author information

Update Dangerfile for example CHANGELOG entry

---

Rakefile

I opted to not use `--fix` for style and instead let the task fail to allow the person issuing the release to fix the style problem.
cc @orta 
Closes: #307

[307] Conform to homebrew PR template

---

CHANGELOG.md
Dangerfile
app/CPReflectionService/Info.plist
app/CocoaPods/Base.lproj/CPHomeWindowController.xib
app/CocoaPods/CPInstallPluginsViewController.swift
app/CocoaPods/Supporting Files/Info.plist
app/CocoaPods/Supporting Files/Localizable.strings

Also bumps the plists for 1.0 proper

Fixes for localizations on the pod plugin install view controller

---

CHANGELOG.md
app/CocoaPods.xcodeproj/project.pbxproj
app/CocoaPods/CPPodFileWindowViewController.swift
app/CocoaPods/Podfile.storyboard

Had to resort to creating a `NSWindowControler` for the editor due to a bug :( See: https://stackoverflow.com/questions/25150223/nswindowcontroller-autosave-using-storyboard?answertab=active#tab-top
Closes: #324 
~~Waiting for the merge of #329 so I can rebase and add a changelog entry~~

[Editor] Remember window sizes across runs

---

CHANGELOG.md
app/CocoaPods/CLI Integrations/CPCLITask.h
app/CocoaPods/CLI Integrations/CPCLITask.m
app/CocoaPods/CPDeintegrateController.swift
app/CocoaPods/CPInstallAction.swift
app/CocoaPods/CPInstallPluginsViewController.swift
app/CocoaPods/CPPodfileInitController.swift
app/CocoaPods/CPSourceRepoCoordinator.swift
app/CocoaPods/NSArray+Helpers.h
app/CocoaPods/NSArray+Helpers.m
bundle-env

I have no idea how `sh` works, but this seems to solve the issue.
Is there some way to add a test for this?
Fixes #331

[bundle-env] Fix error when xcodeproj contains spaces

---

CHANGELOG.md
app/CocoaPods/Base.lproj/CPHomeWindowController.xib

Some of the views are still just using absolute sizing/positions instead of constraints, but since the window size can't change I guess that's not really too big of a problem.
**Screenshots:**
cc @orta

[#321] Match home window size with Xcode

---

app/CocoaPods/CPThickDecorationsWindow.swift

Removed duplicated `NSWindowDidResizeNotification` along with some code cleanup 👌
#trivial

Remove duplicated notification and code cleanup

---

Rakefile
app/CPReflectionService/Info.plist
app/CPReflectionService/RBObject+CocoaPods.m
app/CPReflectionService/RBObject+CocoaPods.rb
app/CocoaPods/Podfile.storyboard
app/CocoaPods/Supporting Files/Info.plist

_almost_ perfect
---
I'm seeing on an app restart windows like this:
Which happens when the window is not the class set inside the storyboard. Looking at that.

Update CocoaPods for 1.1.1

---

CHANGELOG.md
app/CPReflectionService/Info.plist
app/CocoaPods/Supporting Files/Info.plist

Updates from pushing new releases
