CocoaPods/CocoaPods-app

- app/CocoaPods/CPAppDelegate.m
This change makes it possible to install the CLI tool on OS X El Capitan, where the System Integrity Protection feature renders `/usr/bin` unchangeable, even after acquiring root permissions via Authorization Services. See [here](http://asciiwwdc.com/2015/sessions/706) for details on SIP. Note that this change does not affect the “discoverability” of the CLI tool, as `/usr/local/bin` is on the OS X `PATH` by default.
This issue came up in the discussion around #52.
> Change install location for CLI tool

- Rakefile
Xcode places the APR headers in a subdirectory, while the serf build process does not look there. Hence, building serf fails. This commit patches the Rakefile to look in the appropriate subdirectory. This change should not affect building serf otherwise, as if the APR headers are not there, or the subdirectory doesn’t exist in the first place, `clang` will ignore it.
This change was tested on Xcode 7 beta 5 on OS X 10.10.5.
> Fix serf build

- Rakefile
- patches/svn-configure.diff
I found several issues that are causing the embedded Subversion build to fail. This PR centralizes the fixes of these issues. (More commits are coming; the below changes are the first of several.)
As to the removal of the Ruby/Python/Perl integrations: I noted in #64 that these integrations are causing the build to fail. I also feel that these integrations are superfluous as far as CocoaPods-app is concerned, so I feel confident removing them entirely. If you disagree, please say so, though that means I will have to find another solution to the build breakage.
> Fix Subversion build

- app/CocoaPods.xcodeproj/project.pbxproj
- app/CocoaPods/CPCLIToolInstallationController.m
- app/CocoaPods/CPUserProject.m
This PR changes the Xcode deployment target to 10.10, and removes usage of APIs marked as deprecated in that SDK. Note that, as OS X El Capitan is not yet released, I won’t prepare a PR including El Capitan-only APIs for some time. (However, if use of El Capitan APIs is required for #52 to be successfully completed, which is my overarching goal for CocoaPods-app, than so be it.)
I do not know of any reason you may have for keeping the deployment target set to OS X Mountain Lion, seeing as it is now two, soon to be three, releases out of date. However, if there is a reason that I don’t know about, please tell me and I will revise this PR.
> Yosemite Support

- app/CocoaPods/CPUserProject.m
- app/CocoaPods/Supporting Files/Localizable.strings
Without an object to represent the NSTask (and what it actually
represents in CocoaPods terms), I didn’t want to introduce state to
remember what the actual operation (install or update) when it’s more
straightforward to refactor the NSTask logic into its own class that
can represent a named CP task.
> Show a notification when pod install/update tasks complete. (Closes #83)

- app/CocoaPods/CPUserProject.m
Per #82: scrolls to bottom on console append, but only if the user hasn’t scrolled up. If they scroll to the bottom again, it will continue autoscrolling.
> Autoscroll console when appending to it

- app/CocoaPods/CPUserProject.xib
The `rect` that is deleted was moved outside of a UIView subclass, andXcode wouldn't load.
> Fixes a likely bad merge in CPUserProject.xib

- app/CocoaPods/CPAppDelegate.m
Home window shows up if the dock icon is clicked and no other windows are present, mimicking the behavior of Xcode’s welcome window.
> Show the home window on Dock icon click when no other windows are open

- README.markdown
The current README requires a bunch of parsing, and after getting three people bootstrapped I just opted to improve the README with specific instructions. For example, I had still been getting the 10.8 SDK, which I didn't need as I'm not deploying.
> Update the README showing how to get setup if you want to hack

- app/CPReflectionService/CPReflectionService.m
- app/CPReflectionService/CPRubyErrors.h
- app/CPReflectionService/CPRubyErrors.m
- app/CPReflectionService/RBObject+CocoaPods.m
- app/CocoaPods/CPPodfileReflection.m
In reference to https://github.com/CocoaPods/CocoaPods-app/pull/129#discussion_r46500758
@segiddins :tophat::ok_hand:
> [App/Ruby] Create underlying errors for Ruby exception causes.

- app/CocoaPods.xcodeproj/project.pbxproj
- app/CocoaPods/CPAppDelegate.m
- app/CocoaPods/Supporting Files/Info.plist
- app/CocoaPods/URL Handling/URLHandler.swift
Hi everyone!
I took one of the *easy first step* issues and tried to fix it. This PR is related to #44. 
This should be only the first step into an appropriate URL handling feature, but at least now the App can be opened from an URL. I used `cocoapods://` as the URL scheme but if you want to use another just tell me. 
The installation is done in `applicationWillFinishLaunching` as as the [documentation recommends](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/ScriptableCocoaApplications/SApps_handle_AEs/SAppsHandleAEs.html#//apple_ref/doc/uid/20001239-BBCIDFHG) and looks like is the best place in order to work with sandboxing.
I wrote it in Swift, as I'm presuming that this is the direction to go? If not just tell me, is easy enough to write it in Objective-C now …
> Register URL handler

- app/CocoaPods/CPPodfileReflection.m
This is the posible fix that I mentioned in #130. 
*You can see how meanwhile an error is not detected the delay is present, but when there is an error the error moves immediately with the rest of the text.*
> Posible fix for #130 (avoid errors delay in the editor)

- app/CocoaPods/Base.lproj/MainMenu.xib
- app/CocoaPods/CPPodfileEditorViewController.swift
_This is a work in progress_  
I'm working on the ability to toggle comments in the Podfile editor as discussed in #113 
I've currently implemented a single IBAction in the `CPPodfileEditorViewController`. The text editing is provided by two extensions in the same file (`EditorSelection` and `Commenting`). These can be eventually be moved to keep the controller skinny (if you have suggestions, fire away), and can be probably reused in #112 
I provisionally added a menu item to simplify testing, this can be moved out of the way once #144 is resolved.
> Add IBAction to toggle comment to a text selection

- app/CocoaPods/Base.lproj/MainMenu.xib
- app/CocoaPods/CPPodfileEditorViewController.swift
This covers #112 
The indent and outdent is provided with cmd-] and cmd-[ respectively.  
I was able to preserve the user's selection in the text. 
Here's how it works:
As mentioned in #112 two white spaces are used as default.
> Add support for Podfile indentation 

- app/CocoaPods/CPAppDelegate.m
This fixes #149.
Window will be centered on launch. It will remain at the same position after switching to another app.
> Remembers window position

- Rakefile
- app/CPReflectionService/CPReflectionService.m
- app/CPReflectionService/CPReflectionServiceProtocol.h
- app/CPReflectionService/RBObject+CocoaPods.h
- app/CPReflectionService/RBObject+CocoaPods.m
- app/CPReflectionService/RBObject+CocoaPods.rb
- app/CocoaPods.xcodeproj/project.pbxproj
- app/CocoaPods/CPPodfileReflection.m
- app/CocoaPods/Supporting Files/Info.plist
```
2016-01-01 21:09:43.481 CocoaPods[18232:13545945] INFO: {
"pod_targets" =     {
"Pods-Artsy" =         (
AFNetworking,
AFOAuth1Client,
AFNetworkActivityLogger,
SDWebImage,
ALPValidator,
ARGenericTableViewController,
CocoaLumberjack,
FLKAutoLayout,
FXBlurView,
iRate,
ISO8601DateFormatter,
JLRoutes,
JSBadgeView,
JSDecoupledAppDelegate,
Mantle,
MMMarkdown,
NPKeyboardLayoutGuide,
ReactiveCocoa,
UICKeyChainStore,
ARTiledImageView,
ARCollectionViewMasonryLayout,
ORStackView,
"UIView+BooleanAnimations",
NAMapKit,
"UIAlertView+Blocks",
KSDeferred,
MultiDelegate,
ObjectiveSugar,
InterAppCommunication,
"Artsy-UIButtons",
"Artsy+UIColors",
"Artsy+UILabels",
"Artsy+OSSUIFonts",
FBSDKCoreKit,
FBSDKLoginKit,
Analytics,
"ARAnalytics/Segmentio",
"ARAnalytics/HockeyApp",
"ARAnalytics/Adjust", …
```
> [App/Ruby] Get information of user’s projects/targets.

- Rakefile
- app/CocoaPods.xcodeproj/project.pbxproj
Here's a readable version:
Upcoming PR #141  is going to break a lot of people's builds because of the ruby cocoa changes, we want to help them migrate. This offers advice on how.
> Support a versioned build environment

- app/CocoaPods.xcodeproj/project.pbxproj
CPReflector would build before CP.app - so the build phase in CP.app would not error out. Now it's in both.
> Add a check on the reflection tool for mismatched bundled versions

- app/CocoaPods/CPMiniPromise.h
- app/CocoaPods/CPMiniPromise.m
- app/CocoaPods/CPUserProject.m
I was just reading the CPMiniPromise code when I read about it on twitter and noticed that gibberish method name that was probably unintentional. So I fixed it.
> Replace strange word ("forfil") in CPMiniPromiseDelegate method

- app/CocoaPods.xcodeproj/project.pbxproj
- app/CocoaPods/CPPodfileConsoleTextView.swift
- app/CocoaPods/CPPodfileConsoleViewController.swift
- app/CocoaPods/Podfile.storyboard
Fixes #188 by adding `CPPodfileConsoleTextView` to allow the text view to automatically scroll to the bottom if it was previously there. 
I attempted to do this scrolling via utilizing `NSTextView` delegate methods on `CPPodfileConsoleViewController` but none of them had the right order of completion. We must check current position, then append text and then scroll for this action to function correctly.
To do this, I have added an `attributedText` property to the `CPPodfileConsoleTextView` subclass (couldn't override `attributedString` directly). On `didSet` we check the current position then swap out the actual `attributedString` on the text storage and scroll to the previous positioning.
There may be a simpler way to do this than subclassing and adding a property but I couldn't work it …
> Add CPPodfileConsoleTextView to allow auto scrolling

- app/CocoaPods/Base.lproj/CPHomeWindowController.xib
- app/CocoaPods/CPHomeWindowController.m
- app/CocoaPods/CPSidebarDocumentsController.swift
- app/CocoaPods/CPSpotlightDocumentSource.swift
`NSMetadataQueryDidFinishGatheringNotification` is called before `NSMetadataQueryDidUpdateNotification`, but `NSMetadataQueryDidUpdateNotification` is called only when there are files found on the computer. That's why I introduced `queryFinished()` method that is called from `queryGatheringFinished` after delay waiting for `queryUpdated()`.
> Sidebar documents improvements

- app/CocoaPods/CPXcodeInformationGenerator.m
If I switch a Podfile between static libs / frameworks, the uses_frameworks comes through as an `NSNull` and crashes as it doesn't respond to `boolValue`.
> Don't crash when switching between libs/frameworks in a Podfile

- app/CocoaPods.xcodeproj/project.pbxproj
- app/CocoaPods/Base.lproj/MainMenu.xib
- app/CocoaPods/CLI Integrations/CPCLITask.h
- app/CocoaPods/CLI Integrations/CPCLITask.m
- app/CocoaPods/CPDocumentController.swift
- app/CocoaPods/CPPodfileInitController.swift
This adds basic support for running `pod init` on an Xcode Project.
I think it could eventually do with a better interface than just running an open panel?
Fixes https://github.com/CocoaPods/CocoaPods-app/issues/80
> Adds support for running `pod init` on an Xcode Project

- app/CPReflectionService/CPReflectionService.m
- app/CPReflectionService/CPReflectionServiceProtocol.h
- app/CPReflectionService/RBObject+CocoaPods.h
- app/CPReflectionService/RBObject+CocoaPods.rb
- app/CocoaPods/CPPodfileEditorViewController.swift
- app/CocoaPods/CPPodfileViewController.swift
- app/CocoaPods/CPUserProject.h
- app/CocoaPods/CPUserProject.m
- app/CocoaPods/Podfile.storyboard
- app/CocoaPods/Supporting Files/Localizable.strings
Closes #249.
A good way to test this is to edit a `Podfile.lock`'s CocoaPods version to something (say `1.1`) and open the Podfile in the app. It takes a bit of time to get info back from the bridge.
> Lockfile version checking

- app/CocoaPods/CPPodfileInitController.swift
Wanted to get back into the flow, so started testing the app a bit:
Now generates:
> Add support for handling multiple Xcodeprojects in the same folder with pod init

- bundle-env
This fixes https://github.com/CocoaPods/CocoaPods-app/issues/280 and https://github.com/CocoaPods/CocoaPods-app/issues/271 .
> Fix OpenSSL issue in bundled Ruby

- app/CocoaPods/Supporting Files/Info.plist
This hooks the app up to https://github.com/CocoaPods/sparkler. Sparkle passes on profile information from the app through sparkler which saves the metadata and then mirrors the sparkle .xml on the `gh-pages` branch.
This process is outlined [here](https://sparkle-project.org/documentation/system-profiling/).
Fixes #43.
Example of what this results in [here](http://sparkle.psionides.eu/feeds/gitifier/statistics).
> Sparkler for metadata logging and graphs

- Rakefile
- app/CPReflectionService/Info.plist
- app/CocoaPods/Supporting Files/Info.plist
- bundle-env
My internet is too slow to verify this yet, so no merging until this is confirmed ( CI will run through the process - so I'm kinda interested in what happens there )
> Add the Git Credential Helper to the destroot - fixes #259

- app/CPReflectionService/Info.plist
- app/CPReflectionService/RBObject+CocoaPods.rb
- app/CocoaPods/Supporting Files/Info.plist
Closes #273.
This PR depends on https://github.com/CocoaPods/Core/pull/316. We'll have to wait until we get the next CocoaPods release in the app for this PR.
> Use new Pod::Source::Manager

- app/CocoaPods/Base.lproj/CPHomeWindowController.xib
- app/CocoaPods/Base.lproj/MainMenu.xib
- app/CocoaPods/CPInstallAction.swift
- app/CocoaPods/CPMenuVisiblityDirector.swift
- app/CocoaPods/CPPodfileViewController.swift
- app/CocoaPods/Podfile.storyboard
When I started thinking about what the Specs Repo update stuff should look like. I missed the simplest option, and instead went for a more complex but more design-y answer in https://github.com/CocoaPods/CocoaPods-app/issues/260 - thanks for the comments @segiddins 
I think there's probably still a space for something like #260 - but it's vastly reduced it's need now.
and
> Add support for 'auto-update specs repo'

- app/CocoaPods/CPPodfileViewController.swift
Hey guys, first time CocoaPods contributor here.
This PR contains a small fix that prevents multiple popovers to appear when clicking the "show source repo update" button rapidly along with some minor code changes.
Fixes this:
> [PodfileViewController] Prevent showing multiple popovers when clicking the show source repo update btn

- CHANGELOG.md
- app/CocoaPods/Base.lproj/MainMenu.xib
We had a menu item that wasn't hooked up to anything after I re-implmented the Specs repo updating sections.
> Remove the auto repo update button on the main menu

- Rakefile
- test/Podfile
> With the closing of Google Code, the serf project has now become Apache Serf!!
Fixes #326.
> [Rakefile] Update serf endpoint #trivial

- CHANGELOG.md
- app/CocoaPods/CPPodfileEditorViewController.swift
Prevent autocomplete in comments by detecting them an returning `[]` as the completions
Fixes: #328
> [Editor] Disable autocomplete in comments

- CHANGELOG.md
Fixing some formatting and spelling in CHANGELOG.
> [CHANGELOG] Fix formatting and add missing CocoaPods gem links #trivial

- CHANGELOG.md
- app/CocoaPods.xcodeproj/project.pbxproj
- app/CocoaPods/CPFontAndColourGateKeeper.swift
- app/CocoaPods/SMLTextView+OptionClickPopover.swift
- app/CocoaPods/String+Extensions.swift
- app/CocoaPods/Supporting Files/CocoaPods.css
This PR implements #302 - "Allow option clicking on a pod":
- Option click/three finger tap on a pod name to show the popover with the cocoapods pod page
- Hovering the pod name with the option key down will also underline the pod's name
- Clicking on any link inside the popover's `WebView` will redirect the user to the browser
- Custom CSS to remove cocoapods.org global menu from the popover's `WebView`
How it looks:
Would love to get some feedback.
> [Podfile Editor] Allow option clicking on a pod

- app/CocoaPods.xcodeproj/project.pbxproj
- app/CocoaPods/CPAppDelegate.m
- app/CocoaPods/CPDebuggerCheck.h
- app/CocoaPods/CPDebuggerCheck.m
Detect when a debugger is attached and change
the colour of the app icon. Not quite sure how the rotation of the hue works, ideally I guess we'd want to use #5AA6E8
> Adjust the colour of the app icon during dev #trivial

- CHANGELOG.md
- app/CPReflectionService/CPReflectionService.m
- app/CPReflectionService/CPReflectionServiceProtocol.h
- app/CPReflectionService/RBObject+CocoaPods.h
- app/CPReflectionService/RBObject+CocoaPods.rb
- app/CocoaPods/CPPodfileEditorViewController.swift
- app/CocoaPods/SMLTextView+CocoaPods.m
- app/Pods/Fragaria/SMLTextView.m
Relating to #311, this is a rough implementation of looking up pod versions using the reflection service.
While I have some concerns relating to the editor changes —
- some of the logic here could be factored out a little more, and 
- I'm not sure if this is the optimal way to call the reflection service and await a return value —
my primary concern is the changes needed in Fragaria to adjust when completions are allowed and if all options are returned with an empty prefix.
> Discussion: Pod version completion

- CHANGELOG.md
- app/CocoaPods/Base.lproj/MainMenu.xib
- app/CocoaPods/CLI Integrations/CPCLIToolInstallationController.h
- app/CocoaPods/CLI Integrations/CPCLIToolInstallationController.m
- app/CocoaPods/CPAppDelegate.m
- app/CocoaPods/CPHomeWindowController.h
- app/CocoaPods/CPHomeWindowController.m
- app/CocoaPods/Supporting Files/Localizable.strings
* moved creation of CLIToolInstallationController to init of CPHomeWindowController (was in windowDidLoad)
Finally i had some time to put this together. This is my first commit ever for an mac app, so I have no idea if its correct ;-)
~~And I have no idea about the privileged access to remove the binstub how to do it ;)~~ (Solved)
> Added option to remove Command-Line Tool again (#338)

- Dangerfile
- Rakefile
Update the download location for Mercurial.
This is to try to fix the Travis-CI build.
Using the URL used in the [Homebrew formula for Mercurial](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mercurial.rb)
> [Travis-CI] Fix Travis CI build

- README.markdown
- Rakefile
- app/CocoaPods.xcodeproj/project.pbxproj
* Adds hints in README about why 7.3 + El Cap
* Make Rakefile work by moving github headers out
* Our casks got renamed to cocoapods-app
> Updates some deployment notes

- .travis.yml
- CHANGELOG.md
- Rakefile
- app/CPReflectionService/Info.plist
- app/CPReflectionService/RBObject+CocoaPods.m
- app/CocoaPods.xcodeproj/project.pbxproj
- app/CocoaPods/Supporting Files/Info.plist
Prepares for the next CocoaPods release which came out today.
> Prepare for 1.2.0
